// GeneralStaff — interactive-session context sync (T2 of the launchpad plan).
//
// `generalstaff sync --project=<id>` writes a CLAUDE-GS.md file inside the
// registered project's .claude/ directory. The file captures GS's discipline
// surface for that project — mission scope, hands-off boundaries, open task
// queue, and the Hammerstein framing — so an interactive Claude Code session
// started in the project directory has GS's constraints available without
// paste friction.
//
// Claude Code's import syntax (@path/to/file.md at the start of an existing
// CLAUDE.md) pulls this file into the session context on load. Projects
// without an existing CLAUDE.md can reference it manually ("Read
// .claude/CLAUDE-GS.md before making any changes.") in the first prompt of
// a session, or the operator can symlink / cat-append it into a CLAUDE.md
// they already maintain.
//
// Write side is operator-initiated (you run this command), not bot-initiated
// — so hands_off boundaries on `.claude/` only apply to bot cycles, which
// never touch this file anyway.

import { existsSync } from "fs";
import { mkdir, readFile, writeFile } from "fs/promises";
import { dirname, join } from "path";
import { loadProjects } from "./projects";
import { getRootDir } from "./state";
import { loadTasks } from "./tasks";
import type { ProjectConfig, GreenfieldTask } from "./types";

export interface SyncResult {
  project_id: string;
  written: string; // absolute path of the generated file
  mission_present: boolean;
  hands_off_count: number;
  open_tasks: number;
}

export class SyncError extends Error {
  constructor(
    public readonly projectId: string,
    message: string,
  ) {
    super(message);
    this.name = "SyncError";
  }
}

// Short excerpt of the Hammerstein framing — kept in sync with
// CLAUDE.md §Hammerstein context by convention. Updating CLAUDE.md's
// framing means updating this constant too.
const HAMMERSTEIN_EXCERPT = `The short version of the framing this project inherits from Hammerstein's
officer typology: industriousness without judgment is worse than laziness
without judgment, because the damage compounds. A bot (or an interactive
Claude in bot-like mode) is naturally industrious; the operator's job is
to keep that energy aimed at correctness work where "right" is
well-defined, and away from taste work where confident output produces
slop. The MISSION scope and hands-off list below pin down where that
line sits for this specific project. When in doubt, abandon a task and
write a note — that's strictly better than finishing in the wrong
direction.`;

function renderHandsOff(patterns: string[]): string {
  if (patterns.length === 0) {
    return "_(no hands-off patterns — Hard Rule 5 forbids empty lists, so this project likely isn't fully registered yet)_";
  }
  return patterns.map((p) => `- \`${p}\``).join("\n");
}

function renderOpenTasks(tasks: GreenfieldTask[]): string {
  const open = tasks.filter(
    (t) => t.status !== "done" && t.status !== "skipped",
  );
  if (open.length === 0) {
    return "_(queue empty — add tasks via `generalstaff task add --project=<id> --priority=<N> \"...\"`)_";
  }
  const sorted = [...open].sort(
    (a, b) => (a.priority ?? 99) - (b.priority ?? 99),
  );
  return sorted
    .map((t) => {
      const tag = t.interactive_only
        ? " _(interactive-only)_"
        : t.creative
          ? " _(creative)_"
          : "";
      const titlePreview = t.title.length > 200
        ? t.title.slice(0, 200).replace(/\n/g, " ") + "…"
        : t.title.replace(/\n/g, " ");
      return `- **${t.id}** (P${t.priority ?? "?"})${tag}: ${titlePreview}`;
    })
    .join("\n");
}

function renderContext(
  project: ProjectConfig,
  mission: string | null,
  tasks: GreenfieldTask[],
  gsRoot: string,
): string {
  const missionSection = mission
    ? mission.trim()
    : `_(no state/${project.id}/MISSION.md yet — write one to declare scope before relying on this file)_`;

  return `<!--
Generated by GeneralStaff. Re-run \`generalstaff sync --project=${project.id}\`
when MISSION, hands_off, or tasks change. To include in a Claude Code
session, either add \`@.claude/CLAUDE-GS.md\` at the top of the project's
CLAUDE.md, or reference this file by path in the first prompt of the
session.
-->

# GeneralStaff Context — ${project.id}

This project is managed by **GeneralStaff**
(https://github.com/lerugray/generalstaff) as a dispatcher + discipline
layer. Interactive Claude sessions in this directory should operate
within the boundaries below. Bot cycles already do; this file makes the
same surface available to human-in-the-loop work.

**GS root:** \`${gsRoot}\`
**Audit log:** \`${gsRoot}/state/${project.id}/PROGRESS.jsonl\`
**Task queue (canonical):** \`${gsRoot}/state/${project.id}/tasks.json\`

---

## Mission scope

${missionSection}

---

## Hands-off surface

Files the bot refuses to modify (Hard Rule 5, mirrored from
\`projects.yaml\` §${project.id}). Interactive sessions should respect the
same boundaries unless the operator explicitly asks otherwise:

${renderHandsOff(project.hands_off)}

---

## Open tasks

${renderOpenTasks(tasks)}

Use \`generalstaff task done --project=${project.id} --task=<id>\` to mark
a task done (writes to tasks.json and records completion in
PROGRESS.jsonl). Use \`generalstaff task add --project=${project.id} ...\`
to queue new work.

---

## Hammerstein framing

${HAMMERSTEIN_EXCERPT}
`;
}

export async function syncProject(
  projectId: string,
  projectsOverride?: ProjectConfig[],
): Promise<SyncResult> {
  const projects = projectsOverride ?? (await loadProjects());
  const project = projects.find((p) => p.id === projectId);
  if (!project) {
    throw new SyncError(
      projectId,
      `project not registered: ${projectId}. Add it to projects.yaml or run \`generalstaff register\` first.`,
    );
  }

  if (!existsSync(project.path)) {
    throw new SyncError(
      projectId,
      `project path does not exist: ${project.path}`,
    );
  }

  const gsRoot = getRootDir();
  const missionPath = join(gsRoot, "state", project.id, "MISSION.md");
  let mission: string | null = null;
  if (existsSync(missionPath)) {
    try {
      mission = await readFile(missionPath, "utf8");
    } catch {
      mission = null;
    }
  }

  let tasks: GreenfieldTask[] = [];
  try {
    tasks = await loadTasks(project.id);
  } catch {
    tasks = [];
  }

  const targetDir = join(project.path, ".claude");
  await mkdir(targetDir, { recursive: true });
  const targetPath = join(targetDir, "CLAUDE-GS.md");

  const body = renderContext(project, mission, tasks, gsRoot);
  await writeFile(targetPath, body, "utf8");

  return {
    project_id: project.id,
    written: targetPath,
    mission_present: mission !== null,
    hands_off_count: project.hands_off.length,
    open_tasks: tasks.filter(
      (t) => t.status !== "done" && t.status !== "skipped",
    ).length,
  };
}

export async function syncAllProjects(): Promise<SyncResult[]> {
  const projects = await loadProjects();
  const results: SyncResult[] = [];
  for (const project of projects) {
    try {
      results.push(await syncProject(project.id, projects));
    } catch (err) {
      // Fleet-wide sync shouldn't abort on one bad project. Record the
      // failure as a partial result so the CLI can report it.
      const message = err instanceof Error ? err.message : String(err);
      results.push({
        project_id: project.id,
        written: `(failed: ${message})`,
        mission_present: false,
        hands_off_count: project.hands_off.length,
        open_tasks: 0,
      });
    }
  }
  return results;
}
