// Engineering discipline — a "lazy senior dev" minimalism block injected into
// the NON-creative engineer prompt for every provider path.
//
// Distilled from the ponytail skill (github.com/DietrichGebert/ponytail, MIT):
// a YAGNI / stdlib-first ladder that biases the bot toward the minimal solution.
// Mode-B cycles (boilerplate, mechanical refactors) fail by over-engineering,
// not wrong direction — this is the cheap counterweight.
//
// Single source of truth for both engineer paths:
//   - aider:  buildAiderPrompt() embeds ENGINEER_DISCIPLINE directly.
//   - claude: the per-project engineer_command.sh (generated by bootstrap.ts)
//             references $GENERALSTAFF_ENGINEER_DISCIPLINE, which engineer.ts
//             exports into the subprocess env for non-creative cycles only.
//
// Deliberately NOT applied to creative cycles (prose drafting): code-minimalism
// is meaningless there and would only confuse a drafting bot. engineer.ts gates
// the env var on !context.isCreative; buildAiderPrompt only embeds it in the
// non-creative branch.
export const ENGINEER_DISCIPLINE = `## Engineering discipline — lazy senior dev
The best code is the code you never wrote. Before writing anything, climb this
ladder and stop at the first rung that holds:
1. Does this need to exist at all? Speculative need -> skip it, say so in one line. (YAGNI)
2. Does the standard library do it? Use it.
3. Does a native platform feature cover it? Prefer it over a new dependency.
4. Does an already-installed dependency solve it? Use it — never add a new one for what a few lines do.
5. Can it be one line? One line.
6. Only then: the minimum code that works.
Rules: no unrequested abstractions (no interface with one implementation, no
factory for one product, no config for a value that never changes). Deletion over
addition; shortest working diff wins; fewest files. Boring over clever. Mark a
deliberate shortcut with a "ponytail:" comment naming its upgrade path. Never
simplify away input validation at trust boundaries, error handling that prevents
data loss, security, accessibility, or anything the task explicitly requested.`;
